### PR TITLE
Modify `dev:soul` script

### LINKED ISSUE #12: Fix CORS error

### PR DESCRIPTION
**Pull request by ebenezer-melkamu**
Fixes #12 

### Modifications
* Modified the `dev:soul` script to run `chinook.db` and removed the `-c` flag
* Updated `.gitignore` file to ignore `.db-shm` and `-db-wal` files

### CODE REVIEW

**Comment by IanMayo** [comment]
Can we just double-check what we're doing with the `remove -c` please?

We know how young `Soul` is.  Could the `RCO-Soul` issue actually be a sign that something in `Soul` has broken?  IIRC we added `-c` to allow any CORS connections. Maybe it's Soul that needs fixing.

**Comment by ebenezer-melkamu** [comment]
@IanMayo The `-c` flag was my mistake, this is not something that is related to soul, the issue is that we use `-c` to pass list of comma-separated URLs for CORS and i added the flag but i haven't added any URLs and that was a mistake, to allow CORS from any origin you have to pass the `*` sign to the `-c` flag, something like this `-c '*'` and i have double checked everything and everything is working fine.

**Comment by IanMayo** [comment]
It would be useful to verify this, though.  We wish to learn more about the vulnerability to `curl`, particularly if/how we can prevent it.

Could you see if `Soul` can use CORS to block access from `curl`?  It would also be good to double-check that CORS security is working in `Soul`,  I don't think it's covered by a unit test.

**Comment by IanMayo** [comment]
Close, fixed in #14

**Pull request closed without merging**
