### PR TITLE
Modify start script

### PR DESCRIPTION
**Pull request by yinzhidong**
fix  start script use default port 8000

### CODE REVIEW

**Comment by IanMayo** [comment]
Hi, can you give me some background to the PR please? What issue/problem does it address?

**Comment by yinzhidong** [comment]
> Hi, can you give me some background to the PR please? What issue/problem does it address?

## default
the step 3 and 4 by README doc

```shell
npm run dev:soul

npm run dev:client

```

then got the error

image

> the `dev:soul` script use db is ./db/RCO2.sqlite which is not match the script program run by `dev:client`


##  use start script
> so I use the start script

```
npm run start 
```

got the error 
image


so I fix the start script and the run `npm run start` and `npm run dev:client` the app is work

image

**Comment by ebenezer-melkamu** [comment]
Hello @yinzhidong,

Thank you for your PR submission. We appreciate your contribution. After testing, I identified the following two major issues:

1. **CORS Error:** I passed the `-c` flag in the `dev-soul` script and that was causing CORS related errors 
2. **Database Compatibility:** The `RCO.sqlite` database was used in the `dev-soul` script and this database does not contain tables such as `genres` and `Albums`.

* Your fix was correct. However, we need to keep the `start` script as it is for Heroku deployment. Could you please make this adjustment and resubmit your PR? and then you can use the `dev-soul` script to run the `Soul` server

* The new modified scripts will look like this:

    ```js
       "start": "npx soul-cli soul -d ./db/chinook.db -p $PORT -e /app/_extensions",
       "dev:soul": "dotenv -- cross-var soul -d ./db/chinook.db -p %PORT% -e %EXTENSIONS%",
    ```

**Comment by yinzhidong** [comment]
> Hello @yinzhidong,
> 
> Thank you for your PR submission. We appreciate your contribution. After testing, I identified the following two major issues:
> 
> 1. **CORS Error:** I passed the `-c` flag in the `dev-soul` script and that was causing CORS related errors
> 2. **Database Compatibility:** The `RCO.sqlite` database was used in the `dev-soul` script and this database does not contain tables such as `genres` and `Albums`.
> 
> * Your fix was correct. However, we need to keep the `start` script as it is for Heroku deployment. Could you please make this adjustment and resubmit your PR? and then you can use the `dev-soul` script to run the `Soul` server
> * The new modified scripts will look like this:
>   ```js
>      "start": "npx soul-cli soul -d ./db/chinook.db -p $PORT -e /app/_extensions",
>      "dev:soul": "dotenv -- cross-var soul -d ./db/chinook.db -p %PORT% -e %EXTENSIONS%",
>   ```

I commit the code

**Comment by ebenezer-melkamu** [comment]
Hello @yinzhidong,

Thank you once again for your commit. I noticed that you made modifications to the `start` script, allowing it to obtain the `_extensions` folder's `path` by using `-e %EXTENSIONS`. However, this setup didn't work on Heroku. To address this, we had to pass the absolute path of the `_extensions` folder directly in the `start` script.

For development purposes, please use the commands prefixed with `dev:`. Here is the corrected `start` script:

```json
"start": "npx soul-cli soul -d ./db/chinook.db -p $PORT -e /app/_extensions",
```

**Comment by yinzhidong** [comment]
> Hello @yinzhidong,
> 
> Thank you once again for your commit. I noticed that you made modifications to the `start` script, allowing it to obtain the `_extensions` folder's `path` by using `-e %EXTENSIONS`. However, this setup didn't work on Heroku. To address this, we had to pass the absolute path of the `_extensions` folder directly in the `start` script.
> 
> For development purposes, please use the commands prefixed with `dev:`. Here is the corrected `start` script:
> 
> ```json
> "start": "npx soul-cli soul -d ./db/chinook.db -p $PORT -e /app/_extensions",
> ```

ok

**Review by IanMayo — APPROVED** [review]
Thanks for the improved develop-start script @yinzhidong

**Pull request merged**
