### PR TITLE
Add script to start the app as soul extension + modify readme

### PR DESCRIPTION
**Pull request by ebenezer-melkamu**
## Changelog 
1. Add a script to run the react admin app as souls extension 
2. Modify the instructions in the README file 
3. Modify the `.env.sample` file

### CODE REVIEW

**Comment by IanMayo** [comment]
Do we _need_ to install `soul-cli` globally?  I'd rather keep it in the current folder, if we can.  This will make it easier to copy a "working installation" to the client network.

**Comment by IanMayo** [comment]
Note: the instructions suggest we have the same port in two locations:
image


But, the `.env.sample` uses different ports:
image

**Comment by ebenezer-melkamu** [comment]
> Do we _need_ to install `soul-cli` globally? I'd rather keep it in the current folder if we can. This will make it easier to copy a "working installation" to the client network.

In the current setup we do need to install `soul-cli` globally to run the code for development but when installing to Heroku it doesn't require that.

**Comment by ebenezer-melkamu** [comment]
> Note: the instructions suggest we have the same port in two locations: image
> 
> But, the `.env.sample` uses different ports: image

That's a mistake from my side, I will fix the `.env.sample` quickly

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
